<?php



acf_add_local_field_group(array(
    'key' => 'group_619fa2ac258a8',
    'title' => 'Settings',
    'fields' => array(
        array(
            'key' => 'field_619fa2b4be8d9',
            'label' => 'Info',
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
            'selected' => 0,
        ),
        array(
            'key' => 'field_619fa2f9be8da',
            'label' => 'Address',
            'name' => 'address',
            'aria-label' => '',
            'type' => 'link',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
        ),
        array(
            'key' => 'field_62d6eecfa861f',
            'label' => 'Google Maps Iframe',
            'name' => 'google_maps_iframe',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '*On google maps click on share, in the popup switch to the Embed a map tab and click COPY HTML and paste it here. This Iframe will appear at the bottom of the contact us page',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_619fa33fbe8dd',
            'label' => 'Phone',
            'name' => 'phone',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_619fa347be8de',
            'label' => 'Fax',
            'name' => 'fax',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_619fa351be8df',
            'label' => 'Email',
            'name' => 'email',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '33',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_61a917a7b95ea',
            'label' => 'Mass Times',
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
            'selected' => 0,
        ),
        array(
            'key' => 'field_66d21be6bf9c2',
            'label' => 'Use Legacy Mass Times',
            'name' => 'use_legacy_setup',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '*(Dev only. Please don\'t mess with this setting.)',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'allow_in_bindings' => 0,
            'ui_on_text' => 'Legacy',
            'ui_off_text' => 'Modern',
            'ui' => 1,
        ),
        array(
            'key' => 'field_61a917aeb95eb',
            'label' => 'Days',
            'name' => 'mass_times_days',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '*In order for the Mass Times Section on the Homepage to work properly, please sort the days beginning with Sunday and ending with Saturday. If needed you can drag and drop the days on the left',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_66d21be6bf9c2',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'table',
            'pagination' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => 'field_61a918184ed98',
            'button_label' => 'Add Day',
            'rows_per_page' => 20,
            'sub_fields' => array(
                array(
                    'key' => 'field_61a918184ed98',
                    'label' => 'Day',
                    'name' => 'day',
                    'aria-label' => '',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'Monday' => 'Monday',
                        'Tuesday' => 'Tuesday',
                        'Wednesday' => 'Wednesday',
                        'Thursday' => 'Thursday',
                        'Friday' => 'Friday',
                        'Saturday' => 'Saturday',
                        'Sunday' => 'Sunday',
                    ),
                    'default_value' => false,
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                    'parent_repeater' => 'field_61a917aeb95eb',
                ),
                array(
                    'key' => 'field_61a917e9b95ee',
                    'label' => 'Times',
                    'name' => 'mass_times_times',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'collapsed' => 'field_61a9182d4ed99',
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'table',
                    'button_label' => 'Add Time',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_61a9182d4ed99',
                            'label' => 'Label',
                            'name' => 'mass_times_label',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'parent_repeater' => 'field_61a917e9b95ee',
                        ),
                        array(
                            'key' => 'field_61a917f4b95ef',
                            'label' => 'Time',
                            'name' => 'mass_times_time',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                            'parent_repeater' => 'field_61a917e9b95ee',
                        ),
                    ),
                    'rows_per_page' => 20,
                    'parent_repeater' => 'field_61a917aeb95eb',
                ),
            ),
        ),
        array(
            'key' => 'field_66d21b40bf9c1',
            'label' => 'Mass Time',
            'name' => 'new_mass_time_repeater',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_66d21be6bf9c2',
                        'operator' => '!=',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'table',
            'pagination' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => 'field_66d21c4bbf9c3',
            'button_label' => 'Add Row',
            'rows_per_page' => 20,
            'sub_fields' => array(
                array(
                    'key' => 'field_66d21c4bbf9c3',
                    'label' => 'Title',
                    'name' => 'title',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => 20,
                    'allow_in_bindings' => 0,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_66d21b40bf9c1',
                ),
                array(
                    'key' => 'field_66d7575149caf',
                    'label' => 'Show on Homepage?',
                    'name' => 'show_on_homepage',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '*show this column in the banner below the hero on the homepage',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '10',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'allow_in_bindings' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                    'ui' => 1,
                    'parent_repeater' => 'field_66d21b40bf9c1',
                ),
                array(
                    'key' => 'field_66d21d88bf9c7',
                    'label' => 'Times',
                    'name' => 'times_repeater',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'table',
                    'min' => 1,
                    'max' => 0,
                    'collapsed' => 'field_66d21d94bf9c8',
                    'button_label' => 'Add Time',
                    'rows_per_page' => 20,
                    'sub_fields' => array(
                        array(
                            'key' => 'field_66d21d94bf9c8',
                            'label' => 'Start Time',
                            'name' => 'time',
                            'aria-label' => '',
                            'type' => 'time_picker',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'display_format' => 'g:i a',
                            'return_format' => 'g:i a',
                            'allow_in_bindings' => 0,
                            'parent_repeater' => 'field_66d21d88bf9c7',
                        ),
                        array(
                            'key' => 'field_66d72279b6777',
                            'label' => 'End Time',
                            'name' => 'end_time',
                            'aria-label' => '',
                            'type' => 'time_picker',
                            'instructions' => '(optional)',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'display_format' => 'g:i a',
                            'return_format' => 'g:i a',
                            'allow_in_bindings' => 0,
                            'parent_repeater' => 'field_66d21d88bf9c7',
                        ),
                        array(
                            'key' => 'field_66d722adb6778',
                            'label' => 'Language',
                            'name' => 'language',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '(optional)',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => 20,
                            'allow_in_bindings' => 0,
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'parent_repeater' => 'field_66d21d88bf9c7',
                        ),
                        array(
                            'key' => 'field_66d21da2bf9c9',
                            'label' => 'Note',
                            'name' => 'note',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '(optional)',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => 30,
                            'allow_in_bindings' => 0,
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'parent_repeater' => 'field_66d21d88bf9c7',
                        ),
                        array(
                            'key' => 'field_66d21daabf9ca',
                            'label' => 'Show on Homepage?',
                            'name' => 'show_on_homepage',
                            'aria-label' => '',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => '',
                            'default_value' => 0,
                            'allow_in_bindings' => 0,
                            'ui_on_text' => 'Yes',
                            'ui_off_text' => 'No',
                            'ui' => 1,
                            'parent_repeater' => 'field_66d21d88bf9c7',
                        ),
                    ),
                    'parent_repeater' => 'field_66d21b40bf9c1',
                ),
            ),
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'theme-general-settings',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
));